### ISSUE TITLE
Generating cache keys doesn't work in python 3

### ISSUE THREAD

**Issue by pazur** [codeinthehole/django-cacheback#28]
Cache keys are generated using builtin hash method. Python 3.2 introduced hash randomization. Each process salts hashed strings with random value. Therefore key generated by celery worker is different than generated by web worker.

**Comment by nebstrebor** [comment]
Using the built-in hash() method is already a bust for any use on heroku, even on Python 2.  For whatever reason, each heroku dyno (basically, a linux virtual machine instance) will return a different hash() value, even for a simple string (e.g., "test").  It looks like this may also be a problem on GAE. It took me months of getting reports of odd, inexplicable caching behavior before i finally simplified the test case to a server with multiple dynos and realized the same set of parameters were generating different keys on each dyno.

**Comment by codeinthehole** [comment]
See #33 for a proposed fix.
