### ISSUE TITLE
djcelery is a redundant dependency

### ISSUE THREAD

**Issue by yuvadm** [codeinthehole/django-cacheback#29]
New Celery versions do not need djcelery for Django integration. Recommended that this dependency is removed.

I'm trying to work on a patch for this, though it isn't clear how the tests cover this stuff, if at all.

**Comment by bashu** [comment]
and why django<1.7 is mandatory requirement?

**Comment by codeinthehole** [comment]
@bashu I was seeing a few minor issues in tests. I will add Django 1.7 support in v1.0 which I'm hoping to release this week.

**Comment by codeinthehole** [comment]
Now fixed in v1.0
