### ISSUE TITLE
Informer template tag with cacheback

### ISSUE THREAD

**Issue by MikeVL** [codeinthehole/django-cacheback#3]
# Example usage informer_tag #

## In templatetags ##

    @informer_tag(register, 'training/tags/event_tizer.html', 10)
    def event_tizer(object_id):
        instance = Event.objects.get(pk=object_id)
        return {
            'object': instance
        }

## In django template ##

    {% event_tizer 1000 %}

# Template tag code #

    # -*- coding: utf-8 -*-
    from inspect import getargspec
    from django.conf import settings
    from django import template
    from django.template.base import parse_bits
    from django.template import loader
    from django.utils import importlib
    from cacheback.base import Job
    
    
    class InformerJob(Job):
    
        def __init__(self, fn_string, template_name, lifetime=None, fetch_on_miss=None, cache_ttl=None):
            self.fn_string = fn_string
            self.template_name = template_name
    
            if lifetime is not None:
                self.lifetime = int(lifetime)
    
            if fetch_on_miss is not None:
                self.fetch_on_miss = fetch_on_miss
    
            if cache_ttl is not None:
                self.cache_ttl = cache_ttl
    
        def get_context_klass(self):
            return template.Context({
                'MEDIA_URL'   : settings.MEDIA_URL,
                'STATIC_URL'  : settings.STATIC_URL,
            })
    
        def get_constructor_args(self):
            return (self.fn_string, self.template_name)
    
        def get_constructor_kwargs(self):
            return { 'lifetime': self.lifetime, 'cache_ttl': self.cache_ttl }
    
        def fetch(self, *args, **kwargs):
            module_path, fn_name = self.fn_string.split(":")
            module = importlib.import_module(module_path)
            fn = getattr(module, fn_name)
    
            context = self.get_context_klass()
            context.update(fn(*args, **kwargs))
            t = loader.get_template(self.template_name)
            return t.render(context)
    
        def key(self, *args, **kwargs):
            key = super(InformerJob, self).key(self.template_name, *args, **kwargs)
            return '%s:%s' % (self.fn_string, key)
    
    
    
    def informer_tag(register, template_name, lifetime=None, fetch_on_miss=None, cache_ttl=None, name=None):
        def decorator(func):
            params, varargs, varkw, defaults = getargspec(func)
            function_name = (name or getattr(func, '_decorated_function', func).__name__)
    
            class InformerNode(template.Node):
                def __init__(self, fn_string, template_name, *args, **kwargs):
                    self.job_class = InformerJob(fn_string, template_name, lifetime, fetch_on_miss, cache_ttl)
                    self.args = args
                    self.kwargs = kwargs
    
                def get_resolved_arguments(self, context):
                    resolved_args = [var.resolve(context) for var in self.args]
                    resolved_kwargs = dict((k, v.resolve(context)) for k, v in self.kwargs.items())
                    return resolved_args, resolved_kwargs
    
                def render(self, context):
                    resolved_args, resolved_kwargs = self.get_resolved_arguments(context)
                    return self.job_class.get(*resolved_args, **resolved_kwargs)
    
            def wrapper(parser, token):
                bits = token.split_contents()[1:]
                args, kwargs = parse_bits(parser, bits, params, varargs, varkw, defaults, False, function_name)
                return InformerNode('%s:%s' % (func.__module__, func.__name__), template_name, *args, **kwargs)
    
            wrapper.__doc__ = func.__doc__
            register.tag(function_name, wrapper)
            return func
        return decorator

**Comment by codeinthehole** [comment]
Closing as stale
