### ISSUE TITLE
Django 1.7 Support

### ISSUE THREAD

**Issue by ptwobrussell** [codeinthehole/django-cacheback#36]
Are you aware of any reasons that this wouldn't work with Django 1.7? When installing into a Django 1.7 environment, I noticed that it was intentionally scoped to 1.6.

Was really stoked to find this package. It's a terrific design pattern.

**Comment by ptwobrussell** [comment]
After quite a bit of fiddling around, I think the answer is definitely "no, this doesn't work with Django 1.7".

First, I found that I needed to override `Job.key` in order to create a consistent hash from the request so that caching would work. That was easy.

But then I eventually came to understand that `FunctionJob.prepare_args` (I was using a decorator) has a `WSGIRequest` as its `*args`, and it doesn't pickle.

Presumably, neither of these things are issues with Django 1.6, so I take it that something changed with the way requests are passed that will require a little bit of work to get this working.

I'd offer to help, but I'm really not quite sure where to go from here.

Thoughts?

**Comment by ptwobrussell** [comment]
Ok - so sorry for the clutter, but I just wanted to clarify that my problem described in the previous comment was from trying to apply the decorator to a view in urls.py. I can easily workaround the issue by applying the decorator directly to a method as needed. 

Perhaps this makes the entire ticket a moot point unless you planned to support decorators in urls.py. Either way, I'm up an running now. Only other thing I had to do was make sure and declare a `CELERY_IMPORTS=("cacheback.tasks",)` in my settings.py.

**Comment by codeinthehole** [comment]
Django 1.7 support is just something on my todo list I haven't got to yet. Am planning on adding support for the next version but just been busy recently.

The decorator wasn't intended to wrap views originally (I never really considered it tbh).

Were there any other issues affecting Django 1.7 support that you saw?

**Comment by ptwobrussell** [comment]
Once I updated the setup.py to allow Django 1.7, everything seemed to work
fine. The only other thing worth mentioning besides perhaps an explicit
disclaimer about the decorator not being intended for use on views (which
is arguably obvious, but a simple update to the docs might save people some
strife) would be to point out not to use LocMemCache during development.
(Async calls happen when the cache is detected to be stale, but updates
don't seem to ever take.) My experience is that given it's process-based
nature, it doesn't work with django-cacheback. However, using DatabaseCache
works fine for dev and is trivial to get setup.

**Comment by michaelkuty** [comment]
Done in #43

**Comment by o3o3o** [comment]
Hi @ptwobrussell ,
   Please see the #58, You said that you use the decoration with the WSGIRequest as  *args in django1.7.
I had the same problem in django 1.9.5. Can you give me some ideas to solve the problem.
