### ISSUE TITLE
@cacheback decorator and FunctionJob are incompatible with Celery's JSON serializer

### ISSUE THREAD

**Issue by chrisguidry** [codeinthehole/django-cacheback#37]
This took quite some time to debug.  I was using the JSON task serializer for my celery instance, and I observed that the cached data were never refreshed after the initial fetch.

It turns out that serializing tasks as JSON forces all of the strings to unicode.  The `FunctionJob` produces the bytestring names of the module and function to run, and the base `Job` uses the hash of the arguments to create the cache key.  The celery task received the unicode `u'mymodule:myfunction'` and it was hashing to a different value than the original bytes `'mymodule:myfunction'`.  This was causing the celery task to place the updated data into a different key than the webserver had originally placed the data after the first sync.

**Comment by chrisguidry** [comment]
Psuedocode to reproduce, using the 0.9 release:

settings.py
```
.....
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_ACCEPT_CONTENT = ['json']
.....
```

view.py
```
@cacheback(lifetime=10)
def what_time_is_it():
    return datetime.utcnow()

def the_view(request):
    actually_now = datetime.utcnow()
    return HttpResponse(repr([actually_now, what_time_is_it(), actually_now - what_time_is_it()],
                        content_type='text/plain')
```

What you'll see in this case is that the initial call does cache the results, but subsequent calls will continue to use the originally cached results forever.  You won't see any errors coming from the celery tasks, because they are successfully updating the cache at the wrong key.

**Comment by codeinthehole** [comment]
Thanks for the detailed report. I'll have a look into this one shortly.

**Comment by chrisguidry** [comment]
Thanks!  I think the natural solution would be to `.encode('utf-8')` the cache key before queuing the job, but I wasn't quite sure of the best place to do that to make a PR for you.

(PS, love django-cacheback!)

**Comment by jezdez** [comment]
Hm, is https://github.com/codeinthehole/django-cacheback/pull/40 related?

**Comment by chrisguidry** [comment]
That looks very related.

**Comment by codeinthehole** [comment]
I reckon #40 fixes this issue. I can recreate it using the example code above and it disappears when I apply the change in #40. @chrisguidry Let me know if it fixes it for you and I'll do a new release.

Thanks again @jezdez

**Comment by codeinthehole** [comment]
Stale, closing
