### ISSUE TITLE
RemovedInDjango19Warning: 'get_cache' is deprecated in favor of 'caches'

### ISSUE THREAD

**Issue by jgoclawski** [codeinthehole/django-cacheback#41]
With Django 1.8 I get this warning:

> RemovedInDjango19Warning: 'get_cache' is  deprecated in favor of 'caches'.
>    self.cache = get_cache(self.cache_alias)

It's origin is here: https://github.com/codeinthehole/django-cacheback/blob/master/cacheback/base.py#L79

It should be easy to fix and without the fix, django-cacheback will not work with Django 1.9

**Comment by riklaunim** [comment]
The same goes for 
````
RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.
```
