### ISSUE TITLE
Confusing results of to_bytestring method

### ISSUE THREAD

**Issue by mdomans** [codeinthehole/django-cacheback#57]
Cacheback uses [this code](https://github.com/codeinthehole/django-cacheback/blob/master/cacheback/base.py#L22-L33) for the _batteries included_ version of FunctionJob.

Because it calls `str` on the args it can lead to wrong results if the value of that call is same for two **different** objects.

An example of such case are Django models instances which can, for two different objects, have same `str` return value.

Therefore I suggest we either fix this (preferable solution) or expand the docs to document this behaviour.

I'm happy to contribute code on this via a PR - just wanted to touch base first and discuss the direction.

**Comment by stephrdev** [comment]
Hi, I'm not even sure why we should not use force_bytes from django.utils. What do you think? Could we remove the function or does force_bytestring and force_bytes behave differently?

**Comment by mdomans** [comment]
So `force_bytes` and `force_bytestring` really only do that, that is, get you into a situation where given instance is converted to a string. Neither of them is designed to make cache keys.

Now that I look at the state of django utils I don't think any already available function will give proper results, since `str` is not proper solution for cache keys. You can use string as cache keys, but not every result of `str(object)` makes a good key - that's why we have `hash`.

Since the `__hash__` is [documented](https://docs.djangoproject.com/en/1.9/ref/models/instances/#hash) I think we can safely add the basic handling of this case, where, if we have Django model instances as an element of args/kwargs, we call `hash` on it.

It has a few advantages:

 * for vanilla Django objects it will work properly
 * if somebody overrode `__str__` but not `__hash__` it will work properly
 * if somebody overrode `__hash__` - it will work properly

**Comment by stephrdev** [comment]
I like your idea and don't see why we shouldn't try it in addition to replacing to_bytestring.

**Comment by mdomans** [comment]
K, will submit a PR soon
