### ISSUE TITLE
What's missing to support Django 1.10?

### ISSUE THREAD

**Issue by fjsj** [codeinthehole/django-cacheback#65]
Hi, this lib is awesome! I want to use it in a Django 1.10 project, but `setup.py` forces it to support only `<1.10`. Is there any huge incompatibility with 1.10?

**Comment by stephrdev** [comment]
Hi! I think this could work quite easily. Feel free to submit a pull request which updates the dependencies and CI stuff and see if tests work. I'd like to see this happening and am committed to review/merge quickly. Thanks!

**Comment by fjsj** [comment]
Hi @stephrdev , I did the necessary fixes at https://github.com/vintasoftware/django-cacheback/commit/31ade6168619ff3cbb566773cb54b0b570edab25 (build here https://travis-ci.org/vintasoftware/django-cacheback/builds/161784543), but I had to checkout from your `cleanup` branch.

How should I proceed? Will you work on this branch any time soon? If this is the case, I can PR to it. If not, I can take only what is needed from it and PR to master.

**Comment by fjsj** [comment]
@stephrdev any updates?

**Comment by stephrdev** [comment]
Sorry for the late response. Can you create a pull request against the cleanup branch? I hope to merge cleanup to master soon. Some docs are missing at the moment to get the cleanup branch merged.

**Comment by blag** [comment]
If you specify a maximum Django version (like you have done in `setup.py`), you have to update this and push a release to PyPI every time Django releases.

Instead, just remove the maximum Django version requirement, and note the officially supported versions in PyPI and the `README.md`. That way users can upgrade Django if they want without breaking their project. You'll still have to update the CI configuration but you won't be preventing users from upgrading to newer Django versions in the interim.

You can also have Travis test current Django nightly builds while allowing failures for just those tests. That way you have advance notice of anything that breaks cacheback and can fix it before the official Django release.

If this is something you'd consider merging I'll whip up a PR for it.

**Comment by stephrdev** [comment]
For the moment, 1.10 support is added in PR 68. I'm not sure if removing the max. version is the best way because many ppl. maybe don't read the documentation and complain about broken functionality when using newer versions. A faster update on the lib after a Django release might be the better approach.

**Comment by stephrdev** [comment]
Finally, support for 1.10 landed in django-cacheback>=1.2
