### ISSUE TITLE
Scheduler for cache updates

### ISSUE THREAD

**Issue by inoks** [codeinthehole/django-cacheback#82]
I want to have the ability to schedule the cache updates tasks.
For instance, as in the provided example, I want to always have the most recent tweets for the specific user whithout initial timeouts to request data first time.
Do you think it will be a lot of work to create management command in the `django-cacheback` app, which can be started via cron every X minutes to kick off all available cache update tasks asyncronously?

**Comment by stephrdev** [comment]
I think there is nothing we need to add to cacheback to make this possible. An untested example could look like:

    from django.core.management.base import BaseCommand
    from myapp import MyCacheJob
    
    class Command(BaseCommand):
    
        def handle(self, *args, **options):
            MyCacheJob().refresh()

**Comment by inoks** [comment]
That will probably work for my case, thanks!
