### ISSUE TITLE
Job.delete tries to fetch the item before deleting

### ISSUE THREAD

**Issue by mudetz** [codeinthehole/django-cacheback#83]
`Job.delete` does

```python
item = self.cache.get(key)
if item is not None:
    self.cache.delete(key)
```

Why is this the expected behaviour? To me it seems like doing double work just to delete a key, we could just call `self.cache.delete(key)` and save a network call.

**Comment by stephrdev** [comment]
You are right, by definition the Django cache backend makes clear that delete should fail silently. I'd be more than happy to see a PR for that :-)
