### ISSUE TITLE
Support for Django 3.x?

### ISSUE THREAD

**Issue by kennethlove** [codeinthehole/django-cacheback#84]
`django-cacheback` is currently unusable with Django 3.x as `cacheback` uses `django.utils.six` which no longer exists. Any plans or ETA for a new release that supports this newer Django?

**Comment by stephrdev** [comment]
yes, support for Django 3 is a thing. I'll have a look soon to check if there is more to do besides dropping the use of six.

**Comment by nitish-squadrun** [comment]
@stephrdev any update on this? I'd like to use this package on my project that uses Django 3.0 with Python 3.7.
